version: '3.8'

services:
    prod:
        container_name: prod
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/charicrux-api-prod
        ports:
            - 3001:3001
            - 9230:9230
        environment:
            - MONGODB_URI=$MONGODB_URI
            - JWT_SECRET=$JWT_SECRET
            - ROPSTEN_NETWORK_URL=$ROPSTEN_NETWORK_URL
            - MAINNET_NETWORK_URL=$MAINNET_NETWORK_URL
            - RINKEBY_NETWORK_URL=$RINKEBY_NETWORK_URL
            - KOVAN_NETWORK_URL=$KOVAN_NETWORK_URL
            - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
            - METAMASK_WALLET_MNEMONIC=$METAMASK_WALLET_MNEMONIC
            - METAMASK_WALLET_PRIVATE_KEY=$METAMASK_WALLET_PRIVATE_KEY
            - CRYPTO_KEY=$CRYPTO_KEY
        networks:
            - nestjs-network
        restart: unless-stopped
    nginx: 
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/charicrux-api-nginx
        container_name: nginx
        networks:
            - nestjs-network
        depends_on: 
            - prod
        ports: 
            - "80:80"
networks:
    nestjs-network:
